spring:
  application:
    name: masterdata
  datasource:
    url: jdbc:mysql://localhost:3306/db_indomaret?userSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# server:
#   port: 8080
